= Заголовок статьи AsciiDoc
Имя и фамилия <author@asciidoctor.org>
3.0, 29 июля 2022 г.: шаблон статьи AsciiDoc
:оглавление:
: значки: шрифт 
: url-быстрая ссылка: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

Содержимое, вводимое непосредственно под заголовком, но перед заголовком первого раздела, называется преамбулой.

== Заголовок первого уровня

Это абзац, выделенный * жирным* шрифтом и _italicized_ словом.

.Подпись к изображению 
изображение::image-file-name.png [Я - изображение с альтернативным текстом.]

Это еще один абзац. сноска: [Я являюсь текстом сноски и будет отображаться внизу статьи.]

=== Заголовок второго уровня

.Заголовок неупорядоченного списка
* элемент списка 1
** вложенный элемент списка
*** вложенный элемент вложенного списка 1
*** вложенный элемент вложенного списка 2
* элемент списка 2

Это абзац.

. Пример заголовка блока
====
Содержимое блока примеров подлежит обычной замене.
====

.Заголовок боковой панели
****
Боковые панели содержат отложенный текст и могут быть заменены обычным образом.
****

==== Заголовок третьего уровня

[#id-for-listing-block]
.Заголовок блока листинга.
----
Содержимое листингового блока может быть заменено дословно.
Содержимое листингового блока обычно используется для сохранения вводимого кода.
----

===== Заголовок четвертого уровня

.Заголовок таблицы
|===
|Заголовок столбца 1 | Заголовок столбца 2

| Столбец 1, строка 1
| Столбец 2, строка 1

| Столбец 1, строка 2
| Столбец 2, строка 2
|===

====== Заголовок пятого уровня

[цитата, имя-отчество, название фильма]
____
Я - цитата из блока или отрывок из прозы.
Я подвержен обычным заменам.
____

[стих, имя-отчество, название стихотворения и многое другое]
____
Я - стихотворный блок.
 Отступы и концевые строки сохраняются в стихотворных блоках.
____

== Заголовок первого уровня.

СОВЕТ: Есть пять меток с предупреждениями: Совет, Примечание, Важно, Предостережение и Warning.

// Я комментарий и не будет отображаться.

. элемент упорядоченного списка 
.. вложенный элемент упорядоченного списка 
. элемент упорядоченного списка

Текст в конце этого предложения содержит перекрестную ссылку на <<_third_level_heading,заголовок третьего уровня>>

== Заголовок первого уровня

Это ссылка на https://docs.asciidoctor.org/home /[Документация Asciidoctor].
Это ссылка на атрибут {url-quickref} [который связывает этот текст с кратким справочником по синтаксису AsciiDoc].
